mariadb:
  container_name: mariadb
  image: mariadb
  ports: 
    - 3307:3306
  environment:
    - MYSQL_ROOT_PASSWORD="hello123"
  volumes:
    - ${FIWARE_SEC_HOME}/config/mariadb.config:/etc/mysql
    - ${FIWARE_SEC_HOME}/data/mariadb:/var/lib/mysql
    
authzforce:
  build: ./tomcat
  container_name: authzforce
  ports: 
    - 8084:8080
  volumes:
    - ${FIWARE_SEC_HOME}/config/authzforce/conf:/usr/local/tomcat/conf
    - ${FIWARE_SEC_HOME}/data/authzforce/webapps:/usr/local/tomcat/webapps
    - ${FIWARE_SEC_HOME}/data/authzforce/opt.authzforce:/opt/authzforce 
    - ${FIWARE_SEC_HOME}/log/authzforce:/usr/local/tomcat/logs 

idm:
  container_name: idm
  image: fiware/idm
  tty: true
  ports: 
    - 5000:5000
    - 8000:8000
  volumes:
    - ${FIWARE_SEC_HOME}/config/horizon/openstack_dashboard/local:/horizon/openstack_dashboard/local 
    - ${FIWARE_SEC_HOME}/config/keystone/etc:/keystone/etc 
    - ${FIWARE_SEC_HOME}/log/keystone/keystone.log:/var/log/keystone.log
  links:
    - mariadb:mariadb
    - authzforce:authzforce

pep:
  build: ./pep
  container_name: pep
  ports: 
    - 81:80
  volumes:
    - ${FIWARE_SEC_HOME}/data/pep/fiware-pep-proxy:/opt/fiware-pep-proxy 
    - ${FIWARE_SEC_HOME}/log/pep:/var/log/pep
  links:
    - idm:idm 
    - authzforce:authzforce
